init of docs
permitio/docs pull request #349
Opened 2024-05-21 11:26 UTC by RazcoDev

2024-05-22 13:38 UTC, RazcoDev commented on docs/embeddable-uis/element/approval-request.mdx
> +Upon receiving this approval request, the manager reviews it to determine whether to approve this transfer request or not.
Change this

2024-06-09 09:24 UTC, maya-barak requested changes

2024-06-09 09:24 UTC, maya-barak commented on static/img/operation-approval/approval-r-afterSelectResource.png
need to change to updated figma- the actions supposed to be operate, review, approve, deny

2024-06-09 09:24 UTC, maya-barak commented on static/img/operation-approval/approval-r-beforeSelectResource.png
need to change to updated figma- the actions supposed to be operate, review, approve, deny

2024-06-09 09:24 UTC, maya-barak commented on static/img/operation-approval/create-el.png
need to change to updated figma- the actions supposed to be operate, review, approve, deny 

And also if you change the picture- it will be better to change the element name to "operation approval example"

2024-06-09 09:24 UTC, maya-barak commented on docs/embeddable-uis/element/operation-approval.mdx
> +TODO DIAGRAM
you are planning to add diagram ?

2024-06-09 09:24 UTC, maya-barak commented on docs/embeddable-uis/element/operation-approval.mdx
> +For example, if a user wants to seek approval for a $1000 transfer to another user and the key of the resource instance is "transfer-1", they should assign a relevant user with ReBAC permissions in t
the _reviewer_ role display as Italic type and it is supposed to be display with _ before and after the "reviewer"

2024-06-09 09:24 UTC, maya-barak commented on docs/embeddable-uis/element/operation-approval.mdx
> +When the "Operation Approval" Element is created, it will create by default two roles: "_reviewer_" with the permission to review, approve and deny requests, and "_requester_" with the "operate" perm
the reviewer role display as Italic type and it is supposed to be display with _ before and after the "reviewer"

2024-06-09 09:24 UTC, maya-barak commented on docs/embeddable-uis/element/operation-approval.mdx
> +When the "Operation Approval" Element is created, it will create by default two roles: "_reviewer_" with the permission to review, approve and deny requests, and "_requester_" with the "operate" perm
also about the requester

2024-06-09 09:24 UTC, maya-barak commented on docs/embeddable-uis/element/operation-approval.mdx
> +Permit.io Approval Flows is currently in Early Access, and we will gradually open the feature to more users.
is it still relevant ?

2024-06-09 12:46 UTC, maya-barak approved these changes
LGTM- need to add the DIAGRAM

2024-06-19 10:22 UTC, merged