Add Approval Management docs
permitio/docs pull request #358
Opened 2024-05-29 11:19 UTC by shuvyA

![image](https://github.com/permitio/docs/assets/40235290/18672a70-be15-4393-ab5d-de98f822d027)

2024-06-09 10:28 UTC, maya-barak commented on docs/embeddable-uis/element/approval-management.mdx
> +The Approval Management Element is a Frontend component that shows you Operation Approvals. Easily approve or deny Operation Approvals.
Need a better introduction here, maybe add link to operation approval doc

2024-06-09 10:29 UTC, maya-barak requested changes
more info missing

2024-06-09 14:25 UTC, maya-barak commented on docs/embeddable-uis/element/approval-management.mdx
> +The Approval Management Element allows users with an Approver role to manage pending requests. Approver roles are assigned.
"Approver roles are assigned."- what is the meaning ?

2024-06-19 11:20 UTC, RazcoDev approved these changes

2024-06-19 12:41 UTC, maya-barak reviewed
Maybe change "reviewer" role to "Operation Approval Reviewer" or to "_reviewer_"

2024-06-23 08:17 UTC, maya-barak commented on docs/embeddable-uis/element/approval-management.mdx
> +The Approval Management Element allows users with role "Operation Approval Reviewer" to manage pending requests efficiently. The element displays a list of pending requests, and the reviewer can appr
missing explanation about the connection to the operation approval element + add link to the relevant doc (explain that the reviewer role created at the operation element and the developer need to assign the user to this role, also after approve the user who ask the request will assigned to the approver role)

2024-06-23 08:18 UTC, maya-barak commented on docs/embeddable-uis/element/approval-management.mdx
> +The Approval Management Element allows users with role "Operation Approval Reviewer" to manage pending requests efficiently. The element displays a list of pending requests, and the reviewer can appr
missing explanation about the webhook

2024-06-24 10:34 UTC, maya-barak commented on docs/embeddable-uis/element/approval-management.mdx
> +This element based on [Operation Approval element](/embeddable-uis/element/operation-approval), reviewer and approval roles both will be created on the operation approval element. For view the operat
reviewer and approved roles both will be created

2024-06-24 10:34 UTC, maya-barak commented on docs/embeddable-uis/element/approval-management.mdx
> +After the request will approve, the requesting user will be automatically assigned to the approve role (on the relvent resource instance for his request).
will be automatically assigned to the approved role

2024-06-24 10:48 UTC, maya-barak approved these changes
LGTM- fix the approve role

2024-06-24 11:43 UTC, merged