Tk add gist for GitHub
permitio/docs pull request #466
Opened 2024-12-19 21:14 UTC by ocap-kirk

I created a bash script that prompts the user for all the input required to setup an SSH connection. In the docs I just make a tip to link to it, but I could add to the page as well. Let me know what you think.

Link to gist: https://gist.github.com/ocap-kirk/803bdfb4592d6c60a12cc9d6121d5455

2024-12-19 21:16 UTC, ocap-kirk commented
@RazcoDev I added you as reviewer because I know you're helped others in the community with the script and figured you'd be able to test to prove it works :)

2024-12-19 21:53 UTC, RazcoDev reviewed
Looks great - left some comments

2024-12-19 21:53 UTC, RazcoDev commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +Below you'll find how to implement temporary role assignments using ABAC Condition Sets in Permit.io, with a step-by-step implementation guide.
Maybe explain what's temporary role assignment is, and give an example use case for it

2024-12-19 21:53 UTC, RazcoDev commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +The `expires` value above is the Unix timestamp in milliseconds. This requires that the `current_time` value is passed in the `permit.check()` as a user attribute.
Worth to add that it's passed in the check method to fit the condition set that you explain in the next step

2024-12-19 21:53 UTC, RazcoDev commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +    1. Assign the appropriate resource actions to the new "temp-admin" role through the [Policy Editor](https://app.permit.io/policy-editor) after creating the condition set.
Temp admin user set *, not role

2024-12-19 21:53 UTC, RazcoDev commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +            current_time: 1734635473238 //needs to be generate at check time
Maybe set the current time as 'datetime.now()' or some other method that makes sense that it's a programmatic value

2024-12-19 21:53 UTC, RazcoDev commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +- A role called "admin" already created
Must be an admin? Better say it's customizable and in this guide we use Admin

2025-01-06 19:58 UTC, gemanor requested changes
I love this implementation!
Please address the comments (tried to have also suggestions to make it easier 😉)

2025-01-06 19:58 UTC, gemanor commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +            current_time: 1734635473238 //needs to be generate at check time
```suggestion
            current_time: new Date().getTime()
```

2025-01-06 19:58 UTC, gemanor commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +    1. Assign the appropriate resource actions to the new "temp-admin" role through the [Policy Editor](https://app.permit.io/policy-editor) after creating the condition set.
```suggestion
    1. Assign the appropriate resource actions to the new "temp-admin" user set through the [Policy Editor](https://app.permit.io/policy-editor) after creating the condition set.
```

2025-01-06 19:58 UTC, gemanor commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +The `expires` value above is the Unix timestamp in milliseconds. This requires that the `current_time` value is passed in the `permit.check()` as a user attribute.
```suggestion
The `expires` value above is the Unix timestamp in milliseconds. This requires that the `current_time` value be passed in the `permit.check()` as a user attribute. An example of such a `check` function will follow.
```

2025-01-27 08:41 UTC, gemanor commented on docs/how-to/build-policies/abac/temporary_role.mdx
> +## Implementation Steps
@ocap-kirk, since there's no new content here, @filipermit will take it. So no work is needed from your side on this ticket

2025-02-11 16:38 UTC, gemanor commented on docs/how-to/build-policies/abac/time-based-role.mdx
> +Before proceeding, ensure you have the following:
Here is not `Before proceeding` but more `This what we will build`

2025-02-11 16:48 UTC, gemanor commented on docs/how-to/build-policies/abac/time-based-role.mdx
> +## Step 1: Configure Schema & Policy
There is an inconsistency here with # Step and Timeline.

I think the outline should be:
# Step 1: Configure Schema & Policy
1. Configure Tenant Attribute Key
2. Configure time_based_groups User Attribute
3. Create Condition Set
4. Assign Permissions to the Condition Set
# Step 2: Test the Configuration
1. Create a Tenant with the Key coke
2. Create a User with Role & time_based_groups Value
3. Run Permit Check

2025-02-11 19:28 UTC, filipermit commented on docs/how-to/build-policies/abac/time-based-role.mdx
> +Before proceeding, ensure you have the following:
Is it? It's a prerequisite checklist rather than the steps of what we will do

2025-02-13 15:58 UTC, gemanor commented on docs/how-to/build-policies/abac/time-based-role.mdx
> +- A user assigned the `admin` role in both the `default` and `coke` tenants.
```suggestion
- A [Permit.io](https://permit.io) account.
- A **role** called `admin`.
- A **resource** called `internal_api`.
```

2025-02-13 15:59 UTC, gemanor approved these changes

2025-02-13 16:02 UTC, merged